### ISSUE TITLE
Byzantine textform versions

### ISSUE THREAD

**Issue by kylak** [byztxt/byzantine-majority-text#28]
Hello,

I was wondering if it would be possible to have knowledge of the differences between the 2023 version of the text and the 2018 version ? (and also if possible with the 2005 one ?) because I didn't find any information on this subject on https://byzantinetext.com/.

If there are changes in the text between the 2005, 2018, and 2023 versions, would it be possible that Prof. Robison shares few words on that ? (like : why new versions?) or if we could have an official list of textual differences (even if it's possible for anyone to get them by comparing) between those versions ?

Having such a list could help if we use a software such as Logos (it uses the 2005 edition), being helpful to know in which passage we should be careful knowing that a correction/update has been made.

Thanks,
Gustav.

**Comment by normansimonr** [comment]
Hi @kylak! You can consult the Git history of each of the files. Releases 1.0.0 through 2.0.3 contain the RP2005 text with occasional edits from 2005 and 2019. You can see a table of the last edits as of release 1.0.0 [here](https://github.com/byztxt/byzantine-majority-text/releases/tag/v1.0.0). If you look at a specific file like `2CO.CCT`, you can visualise the commit history by using Git Diff (like [here](https://github.com/byztxt/byzantine-majority-text/commit/095d6c69c519d9e4218c97f8c813ea889ca97d9b)).

Each file was edited independently as Dr. Robinson sent updates to @emg over the years, and we don't have a comprehensive list of all the differences between the 2005 text and the text of the 1.0.0 release. It would have to be generated manually file by file. Prior to June 2022 we did not have formal versioning in the repository, and therefore there isn't an automated way to compare RP2005 with RP2018. A manual comparison would be required in my opinion. This is of course complicated by the fact that the 1.0.0 release may or may not reflect RP2018 as the 2018 publication probably did not contain the updates sent by Dr. Robinson to Ulrik in 2019.

A few weeks ago, we released version [3.0.0](https://github.com/byztxt/byzantine-majority-text/releases/tag/v3.0.0) (the current one), which contains the most up-to-date text as of May, 2023. The differences introduced by this version with the previous one are minimal, and you can see them by comparing the generated CSV files of this release with those of release 2.0.3. I for example downloaded [1 Corinthians](https://github.com/byztxt/byzantine-majority-text/blob/v2.0.3/csv-unicode/accents/no-variants/1CO.csv) from the 2.0.3 release and [also](https://github.com/byztxt/byzantine-majority-text/blob/master/csv-unicode/ccat/no-variants/1CO.csv) from the 3.0.0 release and compared them using `git diff` and here is a screenshot of the result (mostly new lines -- the full diff is attached):

![image](https://github.com/byztxt/byzantine-majority-text/assets/6743349/c7a7b0c2-d834-414c-83d5-6146b0911c85)

[diff_1CO.zip](https://github.com/byztxt/byzantine-majority-text/files/12005102/diff_1CO.zip)


You can also use CollateX to mark the differences between 2.0.3 and 3.0.0 if you prefer to work with the XML-TEI files.

I think it really is a pity that comparing between versions is not straightforward, but this obeys to changes in the way the files are encoded (RP2005 used a modified version of Beta Code while release 3.0.0 uses a more standard flavour), as well as to the mismatch between the published printed version numbers (2005, 2016, 2018) and the lack of formal versioning prior to the year 2022 in our repo. I'm not saying creating a changelog is not doable. It definitely is, but at the moment I personally don't have the bandwidth to write code for it. If you or any other person reading this issue can write the necessary code, that would be awesome.

Should professor Robinson decide to publish a new printed version of the Byzantine Text in the future, we would make sure to clearly state which version of the repository corresponds to it in order to avoid confusion. For all intents and purposes, however, the current release is the official and most up-to-date text of the Byzantine Textform, including the apparatuses (the primary line is almost identical to that of RP2005 though). Please note that **the updates contained in the repository are more recent than those you will find in any of the published printed editions.**

**Comment by normansimonr** [comment]
Also, I'll make sure to reach out to Logos and ask them if they would consider switching to the 2023 version. Thanks for reminding me of this!

**Comment by kylak** [comment]
Thanks for your help @normansimonr !

Therefore, does that mean that the 2005 R.P version of Logos would maybe be different than the 2005 R.P version of another bible software ? since that we don't seem to have the perfect electronic version of the 2005 R.P. ?
If that is the case, the only (and first?) electronic version of the R.P which we could easily trust anywhere as R.P 2023 would be this one of May since there's a release clearly associated.

**Comment by normansimonr** [comment]
@kylak That depends on where Logos and other Bible software providers got their RP from. I don't have visibility into that history, unfortunately.

You could go and grab each source file from the 2.0.3 release and pick the initial commit for each one of them, which _may_ get you to the RP2005 edition as it was published by Chilton Press. The Chilton Press edition is the official RP2005, but is a PDF. Back in those days (and really until recently), no official version control was kept of the text, so a situation like the one we're talking about is what you would expect.

> If that is the case, the only (and first?) electronic version of the R.P which we could easily trust anywhere as R.P 2023 would be this one of May since there's a release clearly associated, right ?

The source files present in this repository, including their file histories, are official and are the source of truth of the Byzantine Textform. Files started being added to GitHub back in 2017. For most of the history of the repository, however, they did not exist in Unicode, only as Beta Code. The first release that included Unicode was 1.0.0, but the Unicode converter inserted a number of bugs due to the Beta Code being non-standard. We were finally able to fix those bugs with release 2.0.3.

But you are right that if Logos and other providers got their text at different moments in time, their texts may differ. We are talking about minor differences, mostly in the critical apparatus, however.

In a nutshell:
* Recovering RP2005 from the repository is not straightforward. In case of doubt, you should refer to the PDF.
* There is a possibility that Logos and other providers have different texts, even if all are labelled as RP2005. The differences, though, should be minimal. As I am not familiar with the history of the changes to the text between 2005 and 2017, I sadly cannot provide additional information.
* If you would like to use a previous Unicode text, please use release 2.0.3. **Do not use previous releases** as they contain errors introduced by the Unicode converter (the beta code did not change between release 1.0.0 and 2.0.3, only the Unicode converter and the converted files).
* If you want to study the latest version of the Byzantine Textform, you should definitely use release 3.0.0 (which is up-to-date as of May, 2023). Any new changes will be added here to future releases.

Please let me know if this makes sense!

**Comment by kylak** [comment]
It does make sense ! Thanks a lot for the answer!

**Comment by normansimonr** [comment]
@kylak I've updated the repo's README with additional information that will hopefully clarify things to other people having the same question. Thank you!
