### ISSUE TITLE
Unity of the R.P

### ISSUE THREAD

**Issue by kylak** [byztxt/byzantine-majority-text#36]
I read the pdf that M.Robinson did concerning the R.P (or at least concerning the byzantine text of the N.T), reading it I understood that the R.P text was a text generated from a mix of several manuscripts.

The problem I have is that in the same way that M.Robinson critcizes (I agree with him) most of the modern critiscm for creating in single verses new variants by mixing several manuscripts, I wonder if I haven't the same problem with the R.P if this text is, at a larger level, a created manuscript from several others.

So my question is : Are there for each book of the New Testament R.P a unique greek new testament manuscript from which the R.P New Testament book would be a copy ? Or does the R.P be an ingenious created text ?

The problem is that I don't think that we ought to create the N.T text, but I think we should rather take the best N.T manuscript available because I think that God preserves his Word hence no need to create it. But a created text could I think help to find the good manuscript.

**Comment by normansimonr** [comment]
Hi @kylak. Thank you for your question and comment. Robinson-Pierpont is indeed an _ecclectic edition_ that aims to reconstruct the autographs of the books of the New Testament by applying a majority rule to the many places where individual manuscripts differ from one another. The difference with the _Editio Critica Maior_ and the Nestle-Aland editions is that instead of favouring the readings found in the earliest manuscripts (those manuscripts are very few and are all associated to Egypt), Robinson-Pierpont favours the readings that have the most abundant attestation in the entire tradition. Those majority readings happen to be essentially those of the Kx group of Byzantine manuscripts from the Middle Ages, with some rare exceptions.

If I understand you correctly, what you are interested in is a _diplomatic edition_, ie, the transcription of a single manuscript. You can find the transcriptions of many manuscripts at the website of the Institute for New Testament Textual Research ([here](https://ntvmr.uni-muenster.de/liste)). About 10% of all surviving manuscripts have been transcribed to date. [Here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20001) is for instance the transcription of Codex Sinaiticus (a manuscript that features prominently in the Nestle-Aland editions), and [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31424) is minuscule 1424 (which is normally classified as Byzantine).

I hope these resources help you find what you are looking for.

**Comment by kylak** [comment]
Ok, thanks for the answer!

**Comment by normansimonr** [comment]
Anytime!
